
name: Merge into main branch

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  test-and-merge:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout client repository
        uses: actions/checkout@v3
        
      - name: Fetch all branches
        run: git fetch --all
        
      - name: Checkout main branch
        run: git checkout main
  
      - name: Check last commit for #stable
        id: check_commit
        run: |
          echo "Commit message:"
          git log -1 --pretty=%B
          echo "End of commit message"
          if git log -1 --pretty=%B | grep "#stable"; then
            echo "STABLE_COMMIT=true" >> "$GITHUB_OUTPUT"
          else
            echo "STABLE_COMMIT=false" >> "$GITHUB_OUTPUT"
            echo "Not a stable commit. Exiting."
          fi

      - name: Use Node.js ${{ matrix.node-version }}
        if: ${{ steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'npm'
        
      # - name: Install dependencies
      #   if: ${{ steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
      #   run: npm install

      # - name: Run tests
      #   if: ${{ steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
      #   run: npm run test

      - name: Merge development to main
        if: ${{ success() && steps.check_commit.outputs.STABLE_COMMIT == 'true' }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout main
          git merge development
          git push origin main
          git checkout -b development
          git push origin development
